FROM ubuntu:24.04

# Install required packages
RUN apt update && apt install -y apache2 wget unzip

# Create nagios user with UID 1000
RUN groupadd -g 1000 nagios && \
    useradd -m -u 1000 -g nagios -s /bin/bash nagios

# Create Nagios directory
RUN mkdir -p /usr/local/nagios && \
    chown -R nagios:nagios /usr/local/nagios && \
    chown -R nagios:nagios /var/www

# Switch to non-root user
USER nagios

EXPOSE 8080

CMD ["apache2ctl", "-D", "FOREGROUND"]
